In [6]:
!python -m deeppavlov install insults_kaggle_bert

Requirement already satisfied: torch<1.14.0,>=1.6.0 in /usr/local/lib/python3.9/site-packages (1.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (4.15.0)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (8.5.0.96)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (11.7.99)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (11.7.99)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (11.10.3.66)
Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch<1.14.0,>=1.6.0) (0.45.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch<1.14.0,>=1.6.0) (79.0.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Ignoring transformers: markers 'python_version < "3.8"' don't match your environment
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: transformers==4.30.0 in /usr/local/lib/python3.9/site-packages (4.30.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (2026.1.15)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (3.9.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (0.7.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (2.32.5)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (4.64.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (1.23.5)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (0.36.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (6.0.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (0.13.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (26.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (1.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (4.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests->transformers==4.30.0) (2026.2.25)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests->transformers==4.30.0) (3.11)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.9/site-packages (from requests->transformers==4.30.0) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests->transformers==4.30.0) (2.6.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [7]:
!python -m deeppavlov install rusentiment_bert

Requirement already satisfied: torch<1.14.0,>=1.6.0 in /usr/local/lib/python3.9/site-packages (1.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (4.15.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (11.7.99)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.9/site-packages (from torch<1.14.0,>=1.6.0) (11.7.99)
Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch<1.14.0,>=1.6.0) (0.45.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch<1.14.0,>=1.6.0) (79.0.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Ignoring transformers: markers 'python_version < "3.8"' don't match your environment
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: transformers==4.30.0 in /usr/local/lib/python3.9/site-packages (4.30.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (1.23.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (3.9.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (2026.1.15)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (26.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (0.7.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (0.13.3)
Requirement already satisfied: requests in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (2.32.5)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (6.0.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (4.64.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /usr/local/lib/python3.9/site-packages (from transformers==4.30.0) (0.36.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (4.15.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (1.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests->transformers==4.30.0) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests->transformers==4.30.0) (2026.2.25)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.9/site-packages (from requests->transformers==4.30.0) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests->transformers==4.30.0) (3.11)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [8]:
!pip install pymorphy2 pymorphy2-dicts-ru

Collecting pymorphy2
  Downloading pymorphy2-0.9.1-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 795.4 kB/s eta 0:00:00 0:00:01
Collecting pymorphy2-dicts-ru
  Downloading pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 6.5 MB/s eta 0:00:0000:0100:01
Collecting docopt>=0.6
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting dawg-python>=0.7.1
  Downloading DAWG_Python-0.7.2-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13781 sha256=e163163669b004ba4abd660f90f6ff04776e9dcc7c55827ca686c3610d67b9ba
  Stored in directory: /root/.cache/pip/wheels/70/4a/46/1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b
Successfully built docopt
Installing collected packages: pymorphy2-dicts-ru, docopt, dawg-python, pymorphy2
Successfully installed dawg-python-0.7.2 docopt-0.6.2 pymorphy2-0.9.1 pymorphy2-dicts-ru-2.4.417127.4579844
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [1]:
import pandas as pd
import pymorphy2
from deeppavlov import build_model

# 1. Инициализация лемматизатора для русского языка
morph = pymorphy2.MorphAnalyzer()

def lemmatize_ru(text):
    if not isinstance(text, str): return ""
    return " ".join([morph.parse(word)[0].normal_form for word in text.split()])

# 2. Загрузка моделей DeepPavlov
model_en = build_model("insults_kaggle_bert", download=True)
model_ru = build_model("rusentiment_bert", download=True)

print("Модели загружены и готовы к работе!")

2026-03-11 12:41:37.518 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/datasets/insults_data.tar.gz download because of matching hashes
2026-03-11 12:41:48.56 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/deeppavlov_data/classifiers/insults_kaggle_torch_bert_v5.tar.gz download because of matching hashes
/usr/local/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/usr/local/lib/python3.9/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-03-11 12:43:55.705 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/v1/classifiers/rusentiment_bert/rusentiment_bert_torch.tar.gz download because of matching hashes
Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Модели загружены и готовы к работе!

In [2]:
import pandas as pd
import pymorphy2
from deeppavlov import build_model

# 1. Инициализация инструментов
morph = pymorphy2.MorphAnalyzer()

def lemmatize_ru(text):
    if not isinstance(text, str): return ""
    return " ".join([morph.parse(word)[0].normal_form for word in text.split()])

# Загружаем модели
model_en = build_model("insults_kaggle_bert", download=True)
model_ru = build_model("rusentiment_bert", download=True)

#ЧАСТЬ 1: Английский язык

# Берем первые 500 строк, и указываем, что колонки могут быть "грязными"
df_en = pd.read_csv('toxic_comments.csv', nrows=500, on_bad_lines='skip', engine='python')

# Уберем пустые строки, чтобы модель не ругалась
df_en = df_en.dropna(subset=['text'])

# Берем 10 строк
texts_en = df_en['text'].head(10).astype(str).tolist()
df_en_sample = df_en.head(10).copy()
df_en_sample['predictions'] = model_en(texts_en)

# ЧАСТЬ 2: Русский язык

# Читаем русский датасет
df_ru = pd.read_csv('rusentitweet_full.csv', nrows=500, on_bad_lines='skip', engine='python')
df_ru = df_ru.dropna(subset=['text'])

# Берем 10 строками
df_ru_sample = df_ru.head(10).copy()

# Лемматизация
df_ru_sample['lemmatized_text'] = df_ru_sample['text'].apply(lemmatize_ru)

# Тональность
df_ru_sample['sentiment'] = model_ru(df_ru_sample['lemmatized_text'].tolist())

#ВЫВОД РЕЗУЛЬТАТОВ
print("\n--- Результаты Английский ---")
display(df_en_sample[['text', 'toxic', 'predictions']])

print("\n--- Результаты Русский ---")
display(df_ru_sample[['text', 'lemmatized_text', 'sentiment']])

2026-03-11 12:46:44.577 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/datasets/insults_data.tar.gz download because of matching hashes
2026-03-11 12:46:58.849 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/deeppavlov_data/classifiers/insults_kaggle_torch_bert_v5.tar.gz download because of matching hashes
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-03-11 12:47:34.704 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/v1/classifiers/rusentiment_bert/rusentiment_bert_torch.tar.gz download because of matching hashes
Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

--- Результаты Английский ---

                                                text  toxic predictions
0  Explanation\nWhy the edits made under my usern...      0  Not Insult
1  D'aww! He matches this background colour I'm s...      0  Not Insult
2  Hey man, I'm really not trying to edit war. It...      0  Not Insult
3  "\nMore\nI can't make any real suggestions on ...      0  Not Insult
4  You, sir, are my hero. Any chance you remember...      0  Not Insult
5  "\n\nCongratulations from me as well, use the ...      0  Not Insult
6       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK      1      Insult
7  Your vandalism to the Matt Shirvington article...      0  Not Insult
8  Sorry if the word 'nonsense' was offensive to ...      0  Not Insult
9  alignment on this subject and which are contra...      0  Not Insult

--- Результаты Русский ---

,text,lemmatized_text,sentiment
0,@varlamov @McFaul На,@varlamov @mcfaul на,neutral
1,велл они всё равно что мусор так что ничего с...,велла они всё равно что мусор так что ничего с...,negative
2,"""трезвая жизнь какая-то такая стрёмная""\r\n(с)...","""трезвый жизнь какой-то такой стрёмная"" (с) ар...",neutral
3,Ой какие неожиданные результаты 🤭 https://t.co...,ой какой неожиданный результат 🤭 https://t.co/...,neutral
4,@Shvonder_chief @dimsmirnov175 На заборе тоже ...,@shvonder_chief @dimsmirnov175 на забор тоже н...,neutral
5,@idkwhht мы тоже мебельная компания уджина😳😳😳,@idkwhht мы тоже мебельный компания уджина😳😳😳,positive
6,Счастья здоровья 10 классникам https://t.co/M9...,счастие здоровье 10 классник https://t.co/m9vu...,neutral
7,@dntbliev НЕ ПАЛИ.,@dntbliev не пали.,negative
8,@BTS_twt ты такой красивый 😭😭😭🥺💓,@bts_twt ты такой красивый 😭😭😭🥺💓,positive
9,"@Ladyzchensk Цыган , хуле ...","@ladyzchensk цыган , хула ...",negative